---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: 'true'
  labels:
    k8s-addon: storage-aws.addons.k8s.io
  name: ssd
parameters:
  encrypted: 'true'
  type: gp2
{{if .RetainPD}}
reclaimPolicy: Retain
{{end}}
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
